name: Example Workflow
on:
  push:
    branches: [ main ]
jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Set Output
        run: echo "::set-output name=myOutput::Hello, world^^!"
        id: myStep
      - name: Use Output
        run: echo "${{ steps.myStep.outputs.myOutput }}"
