name: learn command
on:
  workflow_dispatch:
jobs:                                  #各ジョブの詳細を記載する
  hoge:
  　runs-on: [self-hosted]
　　steps:
　　　- id: test_id
        name: test_name
        run: echo "::set-output name=test::hoge"
　　　- run: echo "${{ steps.test_id.outputs.test }}"
